language: python
python:
  - "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python3.2 python2.7
 - pip install PyGithub
 - pip install SPARQLWrapper
 - chmod a+x run_build.py
 - sudo pip install requests
 
 
notifications: 
  on_success: never
 
script: python run_build.py --cov-report term-missing --cov app -v



