
        
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
 
SELECT DISTINCT ?type
WHERE {
  ?s a ?type.
}LIMIT 5

        
        Results
        Number of results
        5
        Type of the results
        literal
        List of results
        http://www.w3.org/2002/07/owl#FunctionalProperty


