
SELECT DISTINCT ?concept
WHERE {
    ?s a ?concept .
} LIMIT 50

        
        Results
        Number of results
        >5
        Type of the results
        uri
        List of results
        http://www.w3.org/2002/07/owl#FunctionalProperty



